//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTill.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Franklin Gothic Medium")]
        public string sFontName {
            get {
                return ((string)(this["sFontName"]));
            }
            set {
                this["sFontName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color cFrmForeColour {
            get {
                return ((global::System.Drawing.Color)(this["cFrmForeColour"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LPT1")]
        public string sPrinterOutputPort {
            get {
                return ((string)(this["sPrinterOutputPort"]));
            }
            set {
                this["sPrinterOutputPort"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REPDATA.DBF")]
        public string sRepDataLoc {
            get {
                return ((string)(this["sRepDataLoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TDATA.DBF")]
        public string sTDataLoc {
            get {
                return ((string)(this["sTDataLoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("THDR.DBF")]
        public string sTHdrLoc {
            get {
                return ((string)(this["sTHdrLoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ACCSTAT.DBF")]
        public string sAccStatLoc {
            get {
                return ((string)(this["sAccStatLoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRANCH.DBF")]
        public string sBranchLoc {
            get {
                return ((string)(this["sBranchLoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTREC.DBF")]
        public string sCustRecLoc {
            get {
                return ((string)(this["sCustRecLoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DETAILS.DBF")]
        public string sDetailsLoc {
            get {
                return ((string)(this["sDetailsLoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PRESETS.DBF")]
        public string sPresetsLoc {
            get {
                return ((string)(this["sPresetsLoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STAFF.DBF")]
        public string sStaffLoc {
            get {
                return ((string)(this["sStaffLoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STKLEVEL.DBF")]
        public string sStkLevelLoc {
            get {
                return ((string)(this["sStkLevelLoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TILLCAT.DBF")]
        public string sTillCatLoc {
            get {
                return ((string)(this["sTillCatLoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STOCK.DBF")]
        public string sStockLoc {
            get {
                return ((string)(this["sStockLoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\INGNG")]
        public string sINGNGDir {
            get {
                return ((string)(this["sINGNGDir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\OUTGNG")]
        public string sOUTGNGDir {
            get {
                return ((string)(this["sOUTGNGDir"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public float fMainScreenFontSize {
            get {
                return ((float)(this["fMainScreenFontSize"]));
            }
            set {
                this["fMainScreenFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bUseVirtualPrinter {
            get {
                return ((bool)(this["bUseVirtualPrinter"]));
            }
            set {
                this["bUseVirtualPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bAutoLowercaseItems {
            get {
                return ((bool)(this["bAutoLowercaseItems"]));
            }
            set {
                this["bAutoLowercaseItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int nSpacesBetweenReceipts {
            get {
                return ((int)(this["nSpacesBetweenReceipts"]));
            }
            set {
                this["nSpacesBetweenReceipts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int nPriceLabelOffset {
            get {
                return ((int)(this["nPriceLabelOffset"]));
            }
            set {
                this["nPriceLabelOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bUseFloppyCashup {
            get {
                return ((bool)(this["bUseFloppyCashup"]));
            }
            set {
                this["bUseFloppyCashup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int nPrinterCharWidth {
            get {
                return ((int)(this["nPrinterCharWidth"]));
            }
            set {
                this["nPrinterCharWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int nLinesAfterReigsterReport {
            get {
                return ((int)(this["nLinesAfterReigsterReport"]));
            }
            set {
                this["nLinesAfterReigsterReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bAutoSwapBootFiles {
            get {
                return ((bool)(this["bAutoSwapBootFiles"]));
            }
            set {
                this["bAutoSwapBootFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bUsingDosInsteadOfFloppy {
            get {
                return ((bool)(this["bUsingDosInsteadOfFloppy"]));
            }
            set {
                this["bUsingDosInsteadOfFloppy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:")]
        public string sFloppyLocation {
            get {
                return ((string)(this["sFloppyLocation"]));
            }
            set {
                this["sFloppyLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color cFrmBackColour {
            get {
                return ((global::System.Drawing.Color)(this["cFrmBackColour"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\till_backup")]
        public string sBackupLocation {
            get {
                return ((string)(this["sBackupLocation"]));
            }
            set {
                this["sBackupLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bDoBackups {
            get {
                return ((bool)(this["bDoBackups"]));
            }
            set {
                this["bDoBackups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bAllowStats {
            get {
                return ((bool)(this["bAllowStats"]));
            }
            set {
                this["bAllowStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sNoStatsAbout {
            get {
                return ((string)(this["sNoStatsAbout"]));
            }
            set {
                this["sNoStatsAbout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bWaitForShutDown {
            get {
                return ((bool)(this["bWaitForShutDown"]));
            }
            set {
                this["bWaitForShutDown"] = value;
            }
        }
    }
}
